coordinator=true
discovery.uri=http://trino:8080

node-scheduler.include-coordinator=true
http-server.https.enabled=false
http-server.http.port=8080
http-server.process-forwarded=true
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
internal-communication.https.required=false

http-server.authentication.allow-insecure-over-http=true

node.environment=production
node.id=coordinator
web-ui.enabled=true