coordinator=true
discovery.uri=http://localhost:8080

http-server.http.port=8080
http-server.process-forwarded=true
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=<secret>

node.environment=production
node.id=trino-coordinator-1