coordinator=false
discovery.uri=http://trino:8080

http-server.http.port=8080

internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
internal-communication.https.required=false

node.environment=production
node.id=worker-${HOSTNAME}

web-ui.enabled=false